/// Flutter icons CardSuitIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CardSuitIcons
///      fonts:
///       - asset: fonts/CardSuitIcons.ttf
///
///
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
///
library;

import 'package:flutter/widgets.dart';

class CardSuitIcons {
  CardSuitIcons._();

  static const _kFontFam = 'CardSuitIcons';
  static const String? _kFontPkg = null;

  static const IconData clovers =
      IconData(0xe96c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diamonds =
      IconData(0xe994, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hearts =
      IconData(0xe9fa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spades =
      IconData(0xeaaa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
